---
latitude: 40.75442
longitude: -73.98577
map_zoom: 12
name: LUMA Hotel Times Square
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 120 West 41st St
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10036'
_hotel_id: LUM399
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
